trigger:
  batch: "true"
  branches:
    include:
      - master
      - devsandbox
jobs:
- job: ProdDeploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
    - task: UseNode@1
    - bash: 
        npm install sfdx-cli --global
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(salesforceProdClientid) --jwtkeyfile ./server.key --username $(salesforceProdUsername) --instanceurl $(salesforceProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
    - bash: 
        sfdx force:source:deploy -l RunLocalTests -p ./force-app -u prod -w 10
      displayName: Deploying Extra Metadata to the Org
- job: devsandboxDeploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/devsandbox'))
  steps:  
  
    - task: UseNode@1
    - bash: 
        npm install sfdx-cli --global
      displayName: Install Salesforce CLI devsandboxDeploy
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(salesforceProdClientid) --jwtkeyfile ./server.key --username $(salesforceProdUsername) --instanceurl $(salesforceProdInstanceUrl) -a prod
      displayName: Authorize devsandboxDeploy org 
    - bash: 
        sfdx force:source:deploy -l RunLocalTests -p ./force-app -u prod -w 10
      displayName: Deploying  Metadata to the devsandboxDeploy