trigger:
  batch: "true"
  branches:
    include:
      - devsandbox
      
jobs:
- job: devsandboxProdDeploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/devsandbox'))
  steps:
    - task: UseNode@1
    - bash: 
        npm install  --global sfdx-cli@7.45.1
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(devsandboxkey) --jwtkeyfile ./server.key --username $(devsandboxus) --instanceurl $(salesforceProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
    - bash: 
        sfdx force:source:deploy -l RunLocalTests -p ./force-app -u prod -w 10
      displayName: Deploying Extra Metadata to the DEVSANDBOX

