trigger:
  batch: "true"
  branches:
    include:
      - master
      - devsandbox
      
      
pr:
  autoCancel: "true"
  branches:
    include:
      - master
      
      
jobs:
- job: PullRequestJob_sandboxDeploy
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  #condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))	
  #condition: and(succeeded(), eq(variables['System.PullRequest.SourceBranch'], 'master') )
  condition:  and(succeeded(), and( eq(variables['System.PullRequest.SourceBranch'], 'devSandbox1'), eq(variables['Build.Reason'], 'PullRequest')))
  steps:
    - task: UseNode@1
    - bash: 
        npm install  --global sfdx-cli@7.45.1
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(salesforceProdClientid) --jwtkeyfile ./server.key --username $(salesforceProdUsername) --instanceurl $(salesforceProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
    #- bash: 
    #    sfdx force:org:create -v prod  edition=developer -a scratchOrg1 
    #  displayName: Create Scratch Org
    #- bash: 
    #    sfdx force:user:password:generate --targetusername scratchOrg1 -v prod
    #  displayName: Generating Scratch Org Password   
    - bash: 
        sfdx force:source:deploy -l RunLocalTests -p ./force-app -u prod -w 10
      displayName: Deploying Extra Metadata to the Org
    - bash: 
      displayName: YE TOH DEV SANDBOX1 H 1
      
- job: CommitJOB_ProdDeploy
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  #condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))	
  #condition: and(succeeded(), eq(variables['System.PullRequest.SourceBranch'], 'master'))
  #condition:  and(succeeded(), and( eq(variables['Build.SourceBranch'], 'refs/heads/devsandbox1'), eq(variables['Build.Reason'], 'IndividualCI')))
  condition:  and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/devsandbox1'))
  steps:
    - task: UseNode@1
    - bash: 
        npm install  --global sfdx-cli@7.45.1
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(salesforceProdClientid) --jwtkeyfile ./server.key --username $(salesforceProdUsername) --instanceurl $(salesforceProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
    #- bash: 
    #    sfdx force:org:create -v prod  edition=developer -a scratchOrg1 
    #  displayName: Create Scratch Org
    #- bash: 
    #    sfdx force:user:password:generate --targetusername scratchOrg1 -v prod
    #  displayName: Generating Scratch Org Password   
    - bash: 
        sfdx force:source:deploy  -p ./force-app -u prod -w 10
      displayName: Deploying Extra Metadata to the Org
    - bash: 
      displayName: YE TOH DEV SANDBOX1 H 1
