trigger:
  batch: "true"
  branches:
    include:
      - master
      - devsandbox
      - devSandbox1
      - devSandbox2
      
pr:
  branches:
    include:
      - master
      - devsandbox
      - devSandbox1      

variables:
- name: one
  value: initialValue 

jobs:
- job: ProdDeploy
  timeoutInMinutes: 10
  condition:  eq(variables['Build.SourceBranch'], 'refs/heads/master')
  continueOnError: true
  steps:
    - task: UseNode@1
    - bash: 
        #npm install   --global  sfdx-cli@7.45.1
        npm install  --global sfdx-cli@7.45.1
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(salesforceProdClientid) --jwtkeyfile ./server2.key --username $(salesforceProdUsername) --instanceurl $(salesforceProdInstanceUrl) -a prod
      displayName: Authorize salesforce org
  


