/* Class Name    : EC_QLProductWrapper
 * Description      :Wrapper Class for EC_QLProduct
 * Created By       :Venkatesh
 * Created On       :2020-Sep-01
 

 * Modification Log:
 * -------------------------------------------------------------------------------
 * Developer                Date            Modification ID         Description
 * -------------------------------------------------------------------------------
 * Venkatesh            2020-Sep-01                              Created the class   
 *
 */
 global class EC_QLProductWrapper {    
    public string sku {get; set;}
    public Decimal quantity {get; set;}
}