/**
 * An apex page controller that exposes the site login functionality
 */
global with sharing class CommunitiesLoginController {
/*
    global CommunitiesLoginController () {}
    
   // Code we will invoke on page load.
    global PageReference forwardToAuthPage() {
     String startUrl =  ApexPages.currentPage().getParameters().get('startURL');
        String displayType =  ApexPages.currentPage().getParameters().get('display');
        return Network.forwardToAuthPage(startUrl, displayType);
    }*/

}