/* Class Name       :EC_EntitlementCacheDTO
 * Description      :wrapper class used in EC_EntitlementCacheDTO
 * Created By       :Rajeshwar Bachu
 * Created On       :14-08-2020
 *
 * Modification Log:
 * ----------------------------------------------------------------------------------------------------------------
 * Developer                Date                Modification ID             Description
 * ----------------------------------------------------------------------------------------------------------------
 * Rajeshwar Bachu         14-08-2020                                   wrapper class used in EC_EntitlementCacheDTO
 * 
 */

public class EC_EntitlementCacheDTO {
    public List<String> productIds;
    }