public with sharing class myclass {
	public myclass() {
		getAppVersion();
		getAppVersion();
    		integer xxxxx;
		integer xxxxx2;
    		System.debug('11111222245');

	}

	public String getAppVersion() {
		integer ii;
		String ss1;
		System.debug('acha to ye baat h');
		System.debug('for testing1');

		system.debug('asdadadasd');
  	    	integer zz;
		System.debug('chnages gqqetAppVersiongetAppVersiongetAppVersiongetAppVersion done');
    		System.debug('for testingeeeeeeeeeee1111111eeeeeeeeeeeeeeeeeee222222');
		System.debug('for tjhhfhgesting1');
    System.debug('for tjhhfhgesting2');
		System.debug('new debug of devsandbox1 branch for testing');
		System.debug('new debug of devsandbox1 branch for testing22222222');
		System.debug('1');
    System.debug('for tjhhfhgesting23');
    Integer YeToDevSandbxo1H1;
    return '1.0.0146';
		
	}
}

